### ISSUE TITLE
Login/Auth Not Working

### ISSUE THREAD

**Issue by dxnside** [SrestMilan/E_Challan_System#2]
• I would like to let you know that the login doesn't seem to work.
• I cant seem to log into the admin account to access the admin panel.
• I hope you can  add authentication before the end of sprint 1.

**Comment by SrestMilan** [comment]
![Screenshot 2022-04-11 144202](https://user-images.githubusercontent.com/77192754/162701757-bb3a99c4-39db-4206-acf3-3b563c0a44eb.png)

Issue is resolved my friend.

**Comment by SrestMilan** [comment]
![login](https://user-images.githubusercontent.com/77192754/162702661-bb414834-d5f5-4d09-93ef-1bd340a4fc30.png)
Issue resolved

**Comment by SrestMilan** [comment]
![logins](https://user-images.githubusercontent.com/77192754/162702927-1e570318-e248-4582-8af9-5a132554bb38.png)
fixed

**Comment by SrestMilan** [comment]
Ok, we will continue our work to solve it before the end of sprint 1.

**Comment by SrestMilan** [comment]
Ok, we will continue our work to solve it before the end of sprint 1.

**Comment by nirajlamichhane63** [comment]
we have to work on solving it as soon as possible............
