### ISSUE TITLE
Broken Login Page

### ISSUE THREAD

**Issue by dxnside** [SrestMilan/E_Challan_System#3]
The login page seems to be broken, please  update the user interface and  fix the UI / UX issues  before the next deliverable.

![Screenshot (44)](https://user-images.githubusercontent.com/87311298/167347570-180260ac-c48e-4149-ad45-55d36645af8f.png)

**Comment by nirajlamichhane63** [comment]
Ok I will look after it and try to solve it as fast as possible

**Comment by nirajlamichhane63** [comment]
ok 
![first](https://user-images.githubusercontent.com/102004926/168297942-ef09d963-5256-4f33-ba32-c6d60fab930f.PNG)
