### ISSUE TITLE
UI / UX Improvements

### ISSUE THREAD

**Issue by dxnside** [SrestMilan/E_Challan_System#4]
### The UI seems doesn't look right in the provided images, the font is inconsistent and color palate you chose seems a bit off . I hope it will be improved before the next deliverable.

![Screenshot (43)](https://user-images.githubusercontent.com/87311298/167347957-7068072e-46a0-4367-8f3c-4068cf20c27f.png)
![Screenshot (47)](https://user-images.githubusercontent.com/87311298/167347966-063188e8-d59e-4447-8c6d-0f7a6fbd0d89.png)
![Screenshot (46)](https://user-images.githubusercontent.com/87311298/167347974-3ea29f13-b34d-433a-8064-ea9c5fd41c6a.png)

**Comment by nirajlamichhane63** [comment]
Issues solved as you can see here

![fourth](https://user-images.githubusercontent.com/102004926/168297591-6c908a75-6c46-47dd-8c09-9a4db0e4610f.PNG)
![second](https://user-images.githubusercontent.com/102004926/168297616-445bd4be-c204-4e82-9f97-ac15b2030bc7.PNG)
![third](https://user-images.githubusercontent.com/102004926/168297622-d41bc4c2-9cbd-40d0-8ee9-21f3296c7c8c.PNG)
